import { createClientFromRequest } from 'npm:@base44/sdk@0.8.6';

async function squareApi(path, accessToken) {
  const url = `https://connect.squareup.com${path}`;
  const resp = await fetch(url, {
    headers: {
      Authorization: `Bearer ${accessToken}`,
      "Content-Type": "application/json",
    },
  });
  const text = await resp.text();
  let json;
  try { 
    json = JSON.parse(text); 
  } catch { 
    json = { raw: text }; 
  }
  if (!resp.ok) {
    throw new Error(`Square API ${path} failed: ${resp.status} ${text}`);
  }
  return json;
}

Deno.serve(async (req) => {
  try {
    const signatureKey = Deno.env.get("SQUARE_WEBHOOK_SIGNATURE_KEY");
    const accessToken = Deno.env.get("SQUARE_ACCESS_TOKEN");
    const publicBaseUrl = Deno.env.get("PUBLIC_BASE_URL") || "https://ritualtexas.com";

    if (!signatureKey || !accessToken) {
      return Response.json({ error: "Missing secrets: SQUARE_WEBHOOK_SIGNATURE_KEY or SQUARE_ACCESS_TOKEN" }, { status: 500 });
    }

    const headerSig = req.headers.get("x-square-hmacsha256-signature");
    if (!headerSig) {
      return Response.json({ error: "Missing x-square-hmacsha256-signature header" }, { status: 400 });
    }

    const rawBody = await req.text();
    const notificationUrl = `${publicBaseUrl}/functions/squareWebhook`;

    // Verify signature using Web Crypto API
    const encoder = new TextEncoder();
    const key = await crypto.subtle.importKey(
      "raw",
      encoder.encode(signatureKey),
      { name: "HMAC", hash: "SHA-256" },
      false,
      ["sign"]
    );
    
    const signatureData = await crypto.subtle.sign(
      "HMAC",
      key,
      encoder.encode(notificationUrl + rawBody)
    );
    
    const expectedSignature = btoa(String.fromCharCode(...new Uint8Array(signatureData)));

    if (headerSig !== expectedSignature) {
      return Response.json({ error: "Invalid Square webhook signature" }, { status: 401 });
    }

    const event = JSON.parse(rawBody);
    const eventType = event?.type || "unknown";

    // ── Payment Link payment: run the deferred booking pipeline ─────────────
    // Fired by Square after a guest pays via the Payment Link generated by
    // guestSubmitBooking. The intake record was persisted in
    // bookingStatus="awaiting_payment" with squareOrderId / squarePaymentLinkId.
    // We now create the Cloudbeds reservation, Acuity appointments, and
    // itinerary email — none of which existed pre-payment.
    if (eventType === "payment.updated" || eventType === "payment.created") {
      const payment = event?.data?.object?.payment;
      const status = payment?.status;
      const orderId = payment?.order_id || "";
      const paymentId = payment?.id || "";
      const eventId = event?.event_id || "";
      const paidAmountCents = Number(payment?.amount_money?.amount) || 0;

      // (A) GUARD — only act on completed payments
      if (status !== "COMPLETED") {
        return Response.json({
          received: true,
          action: "payment_event_skipped",
          eventType,
          status: status || null,
        }, { status: 200 });
      }

      const base44 = createClientFromRequest(req);

      // (B) IDEMPOTENCY — has this event_id already been processed?
      if (eventId) {
        try {
          const seen = await base44.asServiceRole.entities.HotelTreatmentIntake.filter({ squarePaymentEventId: eventId });
          if (seen?.length > 0) {
            return Response.json({
              received: true,
              action: "duplicate_event_ignored",
              eventId,
              intakeId: seen[0].id,
            }, { status: 200 });
          }
        } catch (e: any) {
          console.error("[squareWebhook] Dedup lookup failed (proceeding):", e?.message || e);
        }
      }

      // (C) MATCH — order_id is primary, payment_link_id is fallback
      let intake: any = null;
      if (orderId) {
        try {
          const rows = await base44.asServiceRole.entities.HotelTreatmentIntake.filter({ squareOrderId: orderId });
          if (rows?.length > 0) intake = rows[0];
        } catch (e: any) {
          console.error("[squareWebhook] order_id lookup failed:", e?.message || e);
        }
      }
      if (!intake && payment?.payment_link_id) {
        try {
          const rows = await base44.asServiceRole.entities.HotelTreatmentIntake.filter({ squarePaymentLinkId: payment.payment_link_id });
          if (rows?.length > 0) intake = rows[0];
        } catch (e: any) {
          console.error("[squareWebhook] payment_link_id lookup failed:", e?.message || e);
        }
      }

      if (!intake) {
        console.error(`[squareWebhook] No matching intake for paid Square order. order_id=${orderId} payment_id=${paymentId} event_id=${eventId}`);
        return Response.json({
          received: true,
          action: "no_matching_intake",
          orderId,
          paymentId,
          eventId,
        }, { status: 200 });
      }

      // (D) STATE GUARD — only "awaiting_payment" intakes are eligible
      if (intake.bookingStatus !== "awaiting_payment") {
        return Response.json({
          received: true,
          action: "already_processed",
          intakeId: intake.id,
          bookingStatus: intake.bookingStatus,
        }, { status: 200 });
      }

      // (E) ATOMIC FLIP — flip to processing_booking AND record event_id in one
      // write. Any concurrent event arriving after this point will fail the
      // state guard above on its next read.
      try {
        await base44.asServiceRole.entities.HotelTreatmentIntake.update(intake.id, {
          bookingStatus: "processing_booking",
          squarePaymentEventId: eventId || paymentId || `manual-${Date.now()}`,
          paidAmountCents: paidAmountCents || undefined,
        });
      } catch (e: any) {
        console.error("[squareWebhook] Atomic flip failed:", e?.message || e);
        return Response.json({
          received: true,
          action: "atomic_flip_failed",
          intakeId: intake.id,
          error: String(e?.message || e),
        }, { status: 200 });
      }

      // ── PIPELINE ────────────────────────────────────────────────────────
      let notes = String(intake.internalNotes || "") + `\n[Square payment.updated received — order=${orderId} payment=${paymentId} event=${eventId}]`;
      let hotelBooked = false;
      let treatmentsBooked = false;
      const confirmationCodes: string[] = [];
      let primaryConfirmationCode = "";
      let acuityResultBookings: any[] = [];

      const bookingType = intake.bookingType || "hotel_and_spa";
      const hasRooms = bookingType !== "spa_only" && Array.isArray(intake.rooms) && intake.rooms.length > 0;
      const hasTreatments = bookingType !== "hotel_only" && Array.isArray(intake.selectedTreatments) && intake.selectedTreatments.length > 0;

      // 1. Cloudbeds reservation(s) via intakeBookHotel
      if (hasRooms) {
        try {
          // Flatten rooms[i].guestNames[0] -> rooms[i].guestName for intakeBookHotel.
          // Build a transient copy; do NOT mutate intake.rooms on the persisted record.
          const flattenedRooms = intake.rooms.map((r: any) => ({
            ...r,
            guestName: (Array.isArray(r.guestNames) ? r.guestNames[0] : r.guestName) || intake.guestName,
          }));

          const cbResp = await base44.asServiceRole.functions.invoke("intakeBookHotel", {
            intake: {
              id: intake.id,
              guestName: intake.guestName,
              email: intake.email,
              guestEmail: intake.email,
              phone: intake.phone,
              checkInDate: intake.checkInDate,
              checkOutDate: intake.checkOutDate,
              numberOfGuests: intake.numberOfGuests || 1,
              cloudbedsRoomTypeId: intake.cloudbedsRoomTypeId || flattenedRooms[0]?.roomId || "",
              roomRequested: intake.roomRequested || "",
              rooms: flattenedRooms,
              internalNotes: intake.internalNotes || "",
              treatmentsRequested: intake.treatmentsRequested || "",
            },
          });
          const d: any = cbResp?.data ?? cbResp;
          const reservations: any[] = Array.isArray(d?.reservations) ? d.reservations : [];
          if (reservations.length > 0) {
            for (const r of reservations) {
              if (r?.reservationID) confirmationCodes.push(String(r.reservationID));
            }
            hotelBooked = confirmationCodes.length > 0;
          } else if (d?.reservationID) {
            confirmationCodes.push(String(d.reservationID));
            hotelBooked = true;
          }
          primaryConfirmationCode = confirmationCodes[0] || "";
          if (hotelBooked) {
            notes += `\n[Cloudbeds: ${confirmationCodes.length} reservation(s) created — ${confirmationCodes.join(", ")}]`;
          } else {
            notes += `\n[Cloudbeds booking failed: ${d?.error || d?.message || "no reservation ID returned"}]`;
          }
        } catch (e: any) {
          notes += `\n[Cloudbeds booking failed: ${e?.message || e}]`;
        }
      }

      // 2. Acuity treatments via intakeBookTreatments
      if (hasTreatments) {
        try {
          const acResp = await base44.asServiceRole.functions.invoke("intakeBookTreatments", {
            intake: {
              id: intake.id,
              guestName: intake.guestName,
              email: intake.email,
              phone: intake.phone,
              selectedTreatments: intake.selectedTreatments,
            },
          });
          const d: any = acResp?.data ?? acResp;
          const created: any[] = Array.isArray(d?.bookings) ? d.bookings : [];
          const failed: any[] = Array.isArray(d?.failed) ? d.failed : [];
          acuityResultBookings = created;
          treatmentsBooked = created.length > 0 && failed.length === 0;
          notes += `\n[Acuity: ${created.length} booked, ${failed.length} failed]`;
          if (failed.length > 0) {
            notes += `\n[Acuity failures: ${failed.map((f: any) => `${f.treatmentName || "?"} on ${f.date || "?"}`).join("; ")}]`;
          }
        } catch (e: any) {
          notes += `\n[Acuity booking call failed: ${e?.message || e}]`;
        }
      }

      // 3. Itinerary email — isolated from booking confirmation. Email failure
      // sets `itineraryEmailFailed` for staff visibility but does NOT downgrade
      // bookingStatus, since the guest's reservation is already real in
      // Cloudbeds + Acuity at this point.
      let itineraryEmailFailed = false;
      try {
        const roomNames = hasRooms
          ? intake.rooms.map((r: any) => r.roomName).filter(Boolean).join(", ")
          : "";
        const emailResp: any = await base44.asServiceRole.functions.invoke("sendItineraryEmail", {
          guestName: intake.guestName,
          guestEmail: intake.email,
          confirmationCode: primaryConfirmationCode || intake.id,
          checkIn: intake.checkInDate || null,
          checkOut: intake.checkOutDate || null,
          roomType: roomNames || null,
          spaBookings: acuityResultBookings,
        });
        const emailData: any = emailResp?.data ?? emailResp;
        if (emailData?.error || emailData?.success === false) {
          itineraryEmailFailed = true;
          notes += `\n[Email send failed: ${emailData?.error || "unknown"}]`;
          console.error("[squareWebhook] sendItineraryEmail returned error:", emailData);
        }
      } catch (e: any) {
        itineraryEmailFailed = true;
        notes += `\n[Email send failed: ${e?.message || e}]`;
        console.error("[squareWebhook] sendItineraryEmail threw:", e?.message || e);
      }

      // 4. Final state — bookingStatus only reflects the real booking legs
      // (Cloudbeds + Acuity). Email failure is tracked separately.
      const hotelOk = !hasRooms || hotelBooked;
      const treatmentsOk = !hasTreatments || treatmentsBooked;
      const finalStatus = (hotelOk && treatmentsOk) ? "confirmed" : "needs_manual_review";

      const finalUpdate: Record<string, any> = {
        bookingStatus: finalStatus,
        internalNotes: notes,
        hotelBooked: hotelBooked,
        treatmentsBooked: treatmentsBooked,
        itineraryEmailFailed,
      };
      if (paidAmountCents) finalUpdate.paidAmountCents = paidAmountCents;
      if (confirmationCodes.length > 0) {
        finalUpdate.cloudbedsReservationId = confirmationCodes[0];
        finalUpdate.confirmationCodes = confirmationCodes;
      }

      try {
        await base44.asServiceRole.entities.HotelTreatmentIntake.update(intake.id, finalUpdate);
      } catch (e: any) {
        console.error("[squareWebhook] Final intake update failed:", e?.message || e);
      }

      return Response.json({
        received: true,
        action: "payment_processed",
        intakeId: intake.id,
        bookingStatus: finalStatus,
        hotelBooked,
        treatmentsBooked,
        confirmationCodes,
      }, { status: 200 });
    }

    // ── Invoice payment: mark matching intake as confirmed ──────────────────
    if (eventType === "invoice.payment_made" || eventType === "invoice.updated") {
      const invoice = event?.data?.object?.invoice;
      const invoiceStatus = invoice?.status;
      const isPaid = invoiceStatus === "PAID" || invoiceStatus === "PARTIALLY_PAID";

      if (isPaid || eventType === "invoice.payment_made") {
        const base44 = createClientFromRequest(req);
        // Get customer email from invoice recipient
        const customerId = invoice?.primary_recipient?.customer_id;
        let guestEmail = "";
        if (customerId) {
          try {
            const custResp = await fetch(`https://connect.squareup.com/v2/customers/${encodeURIComponent(customerId)}`, {
              headers: { Authorization: `Bearer ${accessToken}`, "Content-Type": "application/json" },
            });
            const custData = await custResp.json();
            guestEmail = custData?.customer?.email_address || "";
          } catch (e) {
            console.error("Failed to fetch customer for invoice event:", e.message);
          }
        }

        if (guestEmail) {
          try {
            const intakes = await base44.asServiceRole.entities.HotelTreatmentIntake.filter({ email: guestEmail });
            const active = intakes.filter(i => i.bookingStatus !== "confirmed" && i.bookingStatus !== "archived" && i.bookingStatus !== "declined");
            for (const intake of active) {
              await base44.asServiceRole.entities.HotelTreatmentIntake.update(intake.id, { bookingStatus: "confirmed" });
              console.log(`Marked intake ${intake.id} (${guestEmail}) as confirmed via Square invoice payment.`);
            }
          } catch (e) {
            console.error("Failed to update intake on invoice payment:", e.message);
          }
        }

        return Response.json({ received: true, action: "invoice_payment_processed", email: guestEmail }, { status: 200 });
      }

      return Response.json({ received: true, action: "invoice_event_skipped", status: invoiceStatus }, { status: 200 });
    }

    // ── Spa booking events ───────────────────────────────────────────────────
    // Get booking ID from the correct location (without :0 suffix)
    const booking = event?.data?.object?.booking;
    const bookingId = booking?.id;

    if (!bookingId) {
      return Response.json({ received: true, warning: "No booking id in event payload", eventType }, { status: 200 });
    }

    // Use booking data from webhook payload (already complete)
    // No need to fetch again - webhook includes full booking object

    // Fetch customer details for email/phone
    let email = "";
    let phone = "";
    const customerId = booking?.customer_id;
    
    if (customerId) {
      try {
        const custResp = await squareApi(`/v2/customers/${encodeURIComponent(customerId)}`, accessToken);
        email = custResp?.customer?.email_address || "";
        phone = custResp?.customer?.phone_number || "";
      } catch (e) {
        console.error("Failed to fetch customer details:", e.message);
      }
    }

    const startAt = booking?.start_at || "";
    const durationMinutes = booking?.appointment_segments?.[0]?.duration_minutes ?? 0;
    const teamMemberId = booking?.appointment_segments?.[0]?.team_member_id || "";
    const serviceVariationId = booking?.appointment_segments?.[0]?.service_variation_id || "";
    const serviceClientId = booking?.appointment_segments?.[0]?.service_variation_client_id || "";

    // Fetch service name (get parent item, not variation)
    let serviceName = "";
    if (serviceVariationId) {
      try {
        const serviceResp = await squareApi(`/v2/catalog/object/${encodeURIComponent(serviceVariationId)}?include_related_objects=true`, accessToken);
        const variation = serviceResp?.object;
        const parentItemId = variation?.item_variation_data?.item_id;

        // Get parent item name from related objects
        if (parentItemId && serviceResp?.related_objects) {
          const parentItem = serviceResp.related_objects.find(obj => obj.id === parentItemId);
          serviceName = parentItem?.item_data?.name || "";
        }

        // Fallback to variation name if parent not found
        if (!serviceName) {
          serviceName = variation?.item_variation_data?.name || "";
        }
      } catch (e) {
        console.error("Failed to fetch service name:", e.message);
      }
    }

    // Fetch staff name - try retrieving full booking first which may include team member details
    let staffName = "";
    let staffDebugData = null;
    if (teamMemberId) {
      try {
        // Try getting full booking details with team member info
        const bookingResp = await squareApi(`/v2/bookings/${encodeURIComponent(bookingId)}`, accessToken);
        staffDebugData = { bookingResp };

        // Check if team member name is in the appointment segments
        const segments = bookingResp?.booking?.appointment_segments || [];
        const segment = segments[0];
        if (segment?.team_member_name) {
          staffName = segment.team_member_name;
        }

        // If not found, try the team members API
        if (!staffName) {
          const staffResp = await squareApi(`/v2/team_members/${encodeURIComponent(teamMemberId)}`, accessToken);
          staffDebugData.staffResp = staffResp;
          const member = staffResp?.team_member;

          // Try multiple possible name fields
          if (member?.given_name && member?.family_name) {
            staffName = `${member.given_name} ${member.family_name}`.trim();
          } else if (member?.given_name) {
            staffName = member.given_name;
          } else if (member?.family_name) {
            staffName = member.family_name;
          } else if (member?.display_name) {
            staffName = member.display_name;
          } else if (member?.email_address) {
            staffName = member.email_address.split('@')[0];
          }
        }

        console.log("Staff Debug Data:", JSON.stringify(staffDebugData, null, 2));
        console.log("Extracted staff name:", staffName);
      } catch (e) {
        console.error("Failed to fetch staff name:", e.message, e);
        staffDebugData = { error: String(e.message || e) };
      }
    }

    const spaBookingPayload = {
      source: "square",
      squareBookingId: bookingId,
      status: eventType,
      service: serviceClientId || serviceVariationId,
      serviceName: serviceName,
      staff: teamMemberId,
      staffName: staffName,
      startAt,
      durationMinutes,
      price: 0,
      email,
      phone,
      raw: { event, booking, staffDebugData },
      createdAt: new Date().toISOString(),
    };

    // Call attachSpaToItinerary function
    const base44 = createClientFromRequest(req);
    const attachResp = await base44.asServiceRole.functions.invoke('attachSpaToItinerary', spaBookingPayload);

    return Response.json({ received: true, action: attachResp?.data?.action || "processed" }, { status: 200 });
  } catch (err) {
    console.error("squareWebhook error:", err);
    return Response.json({ received: true, error: String(err?.message || err) }, { status: 200 });
  }
});