export const CHECKLIST_TEMPLATES = {
  Kitchen_Open: [
    "Turn on hood vents & exhaust fans",
    "Turn on ovens, grill, flat top & fryers (preheat)",
    "Check & log all refrigerator temps (≤41°F) – log sheet",
    "Check & log all freezer temps (0°F) – log sheet",
    "Verify walk-in cooler door seals & temp (≤41°F)",
    "Set up sanitizer buckets at all stations (200 ppm)",
    "Set up cutting boards – color-coded & clean",
    "Set out clean towels / side towels at each station",
    "Stock hand-washing stations (soap, paper towels)",
    "Inspect all equipment for cleanliness before use",
    "Pull prep list – review with chef",
    "Pull & date-check all items from walk-in (FIFO rotation)",
    "Thaw proteins per schedule – label with date & time",
    "Portion & complete daily mise en place",
    "Prep soups, sauces, stocks as needed",
    "Taste test soups / sauces – adjust seasoning",
    "Stock all line stations to par levels",
    "Check dry goods & dry storage – note low stock to manager",
    "Sharpen & sanitize knives – inspect for damage",
    "Review reservation count & any special dietary needs with manager",
    "Confirm daily specials with FOH team",
    "Confirm allergy / 86'd items board is updated",
    "Chef / lead sign-off – kitchen ready to open",
  ],
  FOH_Open: [
    "Unlock & lights/music on",
    "Sweep dining room",
    "Wipe tables/chairs",
    "Fold napkins (par set)",
    "Roll silverware",
    "Stock stations",
    "Brew tea/coffee",
    "Fill ice bins",
    "Confirm daily special",
    "Confirm soup of the day",
    "Final walkthrough",
  ],
  FOH_Close: [
    "Sanitize tables",
    "Sweep & mop floors",
    "Restock to par",
    "Empty trash",
    "Clean restrooms",
    "Reset tables",
    "Check doors",
    "Turn off music/lights",
    "Lock doors & set alarm",
    "Manager initial / sign-off",
  ],
  KitchenClose: [
    "Turn off grill, flat top, fryers & ovens",
    "Turn off hood vents (after 15 min cool-down)",
    "Filter & store fryer oil – log date",
    "Scrape & clean flat top while warm",
    "Clean & degrease grill grates",
    "Clean burners & drip pans on range",
    "Wipe down all equipment exteriors",
    "Cool all hot food to ≤70°F within 2 hrs (ice bath if needed)",
    "Store & label ALL leftovers (item / date / time / initials)",
    "Wrap & cover all open containers in walk-in",
    "Date & rotate walk-in – discard expired items (FIFO)",
    "Check & log walk-in temps before closing (≤41°F)",
    "Check & log freezer temp (0°F)",
    "Clean fryer baskets & housing",
    "Wipe down & sanitize all prep surfaces & cutting boards",
    "Clean & sanitize all sinks",
    "Empty & sanitize sanitizer buckets",
    "Take out all kitchen trash – replace liners",
    "Sweep then mop all kitchen floors (including walk-in)",
    "Degrease floor mats & reposition",
    "Clean floor drains",
    "Restock line stations for next day open",
    "Write prep notes / carry-over list for next shift",
    "Turn off non-essential lights",
    "Lock walk-in cooler & walk-in freezer",
    "Chef / lead sign-off – kitchen closed & clean",
  ],
  KitchenFoodSafety: [
    "Label: Item / Date / Use By / Initials",
    "No food on floor",
    "Covered storage only",
    "FIFO rotation confirmed",
    "Fridges ≤41°F verified",
    "Freezers 0°F verified",
    "Weekly deep clean log updated",
  ],
  Bar_Open: [
    "Unlock liquor",
    "Stock beer coolers",
    "Fill ice wells",
    "Cut garnishes",
    "Polish glassware",
    "Batch house cocktails",
    "Check wine levels",
  ],
  Bar_Close: [
    "Dump ice wells",
    "Wash mats/tools",
    "Sanitize bar top",
    "Count cash drawer",
    "Log liquor levels",
    "Lock liquor",
    "Turn off taps/lights",
    "Manager initial / sign-off",
  ],
};

export const DEPT_META = {
  Kitchen_Open:      { label: 'BOH – Opening',        time: '60–90 min',  color: 'bg-orange-100 text-orange-800', header: 'bg-orange-50' },
  FOH_Open:          { label: 'FOH – Opening',         time: '60–75 min',  color: 'bg-blue-100 text-blue-800',    header: 'bg-blue-50' },
  FOH_Close:         { label: 'FOH – Closing',         time: '60 min',     color: 'bg-blue-100 text-blue-800',    header: 'bg-blue-50' },
  KitchenClose:      { label: 'BOH – Closing',         time: '90–120 min', color: 'bg-orange-100 text-orange-800', header: 'bg-orange-50' },
  KitchenFoodSafety: { label: 'Kitchen – Food Safety', time: 'daily',      color: 'bg-red-100 text-red-800',      header: 'bg-red-50' },
  Bar_Open:          { label: 'Bar – Opening',         time: '45–60 min',  color: 'bg-purple-100 text-purple-800', header: 'bg-purple-50' },
  Bar_Close:         { label: 'Bar – Closing',         time: '45 min',     color: 'bg-purple-100 text-purple-800', header: 'bg-purple-50' },
};

export const ALL_DEPTS = ['FOH_Open', 'FOH_Close', 'Kitchen_Open', 'KitchenClose', 'KitchenFoodSafety', 'Bar_Open', 'Bar_Close'];